apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QVNJQVQ2WlhLTlBNSEtUWjJNNEo=
  aws_secret_access_key: Q2QzUVhCZmtCd3ZjZVorbmFIV1R4bmdhTkVHQWluUTJaNThFNWpYdg==
  aws_session_token: RndvR1pYSXZZWGR6RUtuLy8vLy8vLy8vL3dFYUROVmdwaDFHWG56MFhqcjU5Q0xWQWZDZzhTMlBkY29MazJCVkMyMFc3VnVqMHFvQWQxZmV0cWlaaWl2RlFuMlJKRDk5OHhUNG10d1pkdElleFNnMEdSSkNyalJMSFFxeU9zc2M4eEpSRFNPNDU5bnF4b3RuN2k1d2hLMzF1KzFlbUE1WWJWNkhheXFVaUhRcWtlODdsZkhOblZXcHV2ZGpvL1VybHN4WXdkRzFhQXhDSUNUSHZPWWptSW50UWFHK2psQ015Y3gwbEZGMWp1MUpYWlZLUW9MMitseXZpTjF0dFV2a2J6M0Z1RmNsbkM5ODZ1U0dRVnkzYTJuMnJjZkZ5WDNSdUNRbncrNGdEZW9VcDlMRit2QkY1c3A3d0dFTFZsL1RKbkZFM2s0N2x4Yzk1Q2pWd2FDWkJqSXRPSzdMYkVKcGJFNVNZREwxRCtZUmE3K2VWdGlYWkpLcXZFUTl0QVJFWXk2RlBjQzhPTEhLRGx1SVBjVS8=